import { getTableName } from "drizzle-orm";
import { describe, expect, it } from "vitest";

import {
  agentEvents,
  agentSessions,
  collaborationConflictResolutions,
  coordinationMessages,
  designPartnerFeedback,
  githubIssueAssignments,
  pathClaims,
  publishedBranches,
  providerCredentialEvents,
  providerCredentials,
  cliAccessTokens,
  cliDeviceAuthorizations,
  sandboxRuntimeIntervals,
  userComputeUsage,
  userEnvironmentVariables,
  users,
  workspaceMembers,
  workspaceRuntimes,
  workspaces,
  worktrees,
  yjsSnapshots,
} from "./schema";

describe("database schema", () => {
  it("defines the core workspace tables", () => {
    expect(getTableName(workspaces)).toBe("workspaces");
    expect(workspaces.repositoryVisibility.name).toBe("repository_visibility");
    expect(workspaceRuntimes.provisionedHeadSha.name).toBe(
      "provisioned_head_sha",
    );
    expect(getTableName(designPartnerFeedback)).toBe("design_partner_feedback");
    expect(getTableName(workspaceMembers)).toBe("workspace_members");
    expect(getTableName(agentSessions)).toBe("agent_sessions");
    expect(getTableName(agentEvents)).toBe("agent_events");
    expect(agentSessions.workflowRunId.name).toBe("workflow_run_id");
    expect(agentSessions.provider.name).toBe("provider");
    expect(agentEvents.idempotencyKey.name).toBe("idempotency_key");
    expect(getTableName(githubIssueAssignments)).toBe(
      "github_issue_assignments",
    );
    expect(getTableName(pathClaims)).toBe("path_claims");
    expect(getTableName(coordinationMessages)).toBe("coordination_messages");
    expect(getTableName(yjsSnapshots)).toBe("yjs_snapshots");
    expect(yjsSnapshots.stateVector.name).toBe("state_vector_base64");
    expect(yjsSnapshots.filesystemContents.name).toBe("filesystem_contents");
    expect(yjsSnapshots.hasConflict.name).toBe("has_conflict");
    expect(getTableName(collaborationConflictResolutions)).toBe(
      "collaboration_conflict_resolutions",
    );
    expect(coordinationMessages.correlationId.name).toBe("correlation_id");
    expect(worktrees.reviewDiffDigest.name).toBe("review_diff_digest");
    expect(worktrees.mergedAt.name).toBe("merged_at");
    expect(getTableName(publishedBranches)).toBe("published_branches");
    expect(getTableName(providerCredentials)).toBe("provider_credentials");
    expect(getTableName(cliDeviceAuthorizations)).toBe(
      "cli_device_authorizations",
    );
    expect(getTableName(cliAccessTokens)).toBe("cli_access_tokens");
    expect(providerCredentials.status.name).toBe("status");
    expect(providerCredentials.encryptedMaterial.name).toBe(
      "encrypted_material",
    );
    expect(getTableName(providerCredentialEvents)).toBe(
      "provider_credential_events",
    );
    expect(getTableName(userEnvironmentVariables)).toBe(
      "user_environment_variables",
    );
    expect(userEnvironmentVariables.encryptedValue.name).toBe(
      "encrypted_value",
    );
    expect(getTableName(userComputeUsage)).toBe("user_compute_usage");
    expect(userComputeUsage.minutesUsed.name).toBe("minutes_used");
    expect(getTableName(sandboxRuntimeIntervals)).toBe(
      "sandbox_runtime_intervals",
    );
    expect(sandboxRuntimeIntervals.endedAt.name).toBe("ended_at");
    expect(users.passwordHash.name).toBe("password_hash");
    expect(users.googleUserId.name).toBe("google_user_id");
    expect(providerCredentials.scopeType.name).toBe("scope_type");
    expect(providerCredentials.encryptedAccessToken.name).toBe(
      "encrypted_access_token",
    );
    expect(providerCredentials.awsRoleArn.name).toBe("aws_role_arn");
    expect(publishedBranches.sourceHeadSha.name).toBe("source_head_sha");
    expect(publishedBranches.remoteRef.name).toBe("remote_ref");
    expect(publishedBranches.pullRequestNumber.name).toBe(
      "pull_request_number",
    );
    expect(publishedBranches.pullRequestUrl.name).toBe("pull_request_url");
    expect(yjsSnapshots.conflictResolvedBy.name).toBe("conflict_resolved_by");
  });
});
