import { getTableName } from "drizzle-orm";
import { describe, expect, it } from "vitest";

import {
  agentEvents,
  agentSessions,
  collaborationConflictResolutions,
  conversationArtifacts,
  conversationMessages,
  conversations,
  coordinationMessages,
  designPartnerFeedback,
  githubIssueAssignments,
  featureOverrideAuditEvents,
  organizationFeatureOverrides,
  organizationMembers,
  organizationRole,
  organizations,
  organizationSubscriptionStatus,
  organizationSubscriptions,
  pathClaims,
  planEntitlements,
  plans,
  subscriptionPlan,
  publishedBranches,
  providerCredentialEvents,
  providerCredentials,
  cliAccessTokens,
  cliDeviceAuthorizations,
  sandboxRuntimeIntervals,
  sharedChatMembers,
  sharedChatInvites,
  sharedChats,
  userComputeUsage,
  userEnvironmentVariables,
  userFeatureOverrides,
  featureKey,
  users,
  workspaceMembers,
  workspaceRuntimeAssignments,
  workspaceRuntimes,
  runtimeHosts,
  workspaces,
  worktrees,
  yjsSnapshots,
} from "./schema";

describe("database schema", () => {
  it("keeps entitlement enum values aligned with the public contracts", () => {
    expect(organizationRole.enumValues).toEqual([
      "owner",
      "admin",
      "billing_admin",
      "member",
    ]);
    expect(subscriptionPlan.enumValues).toEqual([
      "free",
      "pro",
      "team",
      "enterprise",
    ]);
    expect(organizationSubscriptionStatus.enumValues).toEqual([
      "trialing",
      "active",
      "past_due",
      "canceled",
    ]);
    expect(featureKey.enumValues).toEqual(["hosted_codex_subscription"]);
  });

  it("defines the core workspace tables", () => {
    expect(getTableName(workspaces)).toBe("workspaces");
    expect(getTableName(organizations)).toBe("organizations");
    expect(getTableName(organizationMembers)).toBe("organization_members");
    expect(getTableName(plans)).toBe("plans");
    expect(getTableName(planEntitlements)).toBe("plan_entitlements");
    expect(getTableName(organizationSubscriptions)).toBe(
      "organization_subscriptions",
    );
    expect(getTableName(organizationFeatureOverrides)).toBe(
      "organization_feature_overrides",
    );
    expect(getTableName(userFeatureOverrides)).toBe("user_feature_overrides");
    expect(getTableName(featureOverrideAuditEvents)).toBe(
      "feature_override_audit_events",
    );
    expect(workspaces.organizationId.name).toBe("organization_id");
    expect(workspaces.organizationId.notNull).toBe(true);
    expect(organizationMembers.role.name).toBe("role");
    expect(organizationSubscriptions.planId.name).toBe("plan_id");
    expect(planEntitlements.feature.name).toBe("feature");
    expect(organizationFeatureOverrides.expiresAt.name).toBe("expires_at");
    expect(userFeatureOverrides.createdBy.name).toBe("created_by");
    expect(featureOverrideAuditEvents.previousEnabled.name).toBe(
      "previous_enabled",
    );
    expect(getTableName(conversations)).toBe("conversations");
    expect(getTableName(conversationMessages)).toBe("conversation_messages");
    expect(getTableName(conversationArtifacts)).toBe("conversation_artifacts");
    expect(getTableName(sharedChats)).toBe("shared_chats");
    expect(getTableName(sharedChatMembers)).toBe("shared_chat_members");
    expect(getTableName(sharedChatInvites)).toBe("shared_chat_invites");
    expect(sharedChatInvites.encryptedToken.name).toBe("encrypted_token");
    expect(conversationMessages.sourceContentType.name).toBe(
      "source_content_type",
    );
    expect(workspaces.repositoryVisibility.name).toBe("repository_visibility");
    expect(workspaceRuntimes.provisionedHeadSha.name).toBe(
      "provisioned_head_sha",
    );
    expect(getTableName(runtimeHosts)).toBe("runtime_hosts");
    expect(runtimeHosts.freeWorkspaceSlots.name).toBe("free_workspace_slots");
    expect(getTableName(workspaceRuntimeAssignments)).toBe(
      "workspace_runtime_assignments",
    );
    expect(workspaceRuntimeAssignments.fencingToken.name).toBe("fencing_token");
    expect(getTableName(designPartnerFeedback)).toBe("design_partner_feedback");
    expect(getTableName(workspaceMembers)).toBe("workspace_members");
    expect(getTableName(agentSessions)).toBe("agent_sessions");
    expect(getTableName(agentEvents)).toBe("agent_events");
    expect(agentSessions.workflowRunId.name).toBe("workflow_run_id");
    expect(agentSessions.provider.name).toBe("provider");
    expect(agentEvents.idempotencyKey.name).toBe("idempotency_key");
    expect(getTableName(githubIssueAssignments)).toBe(
      "github_issue_assignments",
    );
    expect(getTableName(pathClaims)).toBe("path_claims");
    expect(getTableName(coordinationMessages)).toBe("coordination_messages");
    expect(getTableName(yjsSnapshots)).toBe("yjs_snapshots");
    expect(yjsSnapshots.stateVector.name).toBe("state_vector_base64");
    expect(yjsSnapshots.filesystemContents.name).toBe("filesystem_contents");
    expect(yjsSnapshots.hasConflict.name).toBe("has_conflict");
    expect(getTableName(collaborationConflictResolutions)).toBe(
      "collaboration_conflict_resolutions",
    );
    expect(coordinationMessages.correlationId.name).toBe("correlation_id");
    expect(worktrees.reviewDiffDigest.name).toBe("review_diff_digest");
    expect(worktrees.mergedAt.name).toBe("merged_at");
    expect(getTableName(publishedBranches)).toBe("published_branches");
    expect(getTableName(providerCredentials)).toBe("provider_credentials");
    expect(getTableName(cliDeviceAuthorizations)).toBe(
      "cli_device_authorizations",
    );
    expect(getTableName(cliAccessTokens)).toBe("cli_access_tokens");
    expect(providerCredentials.status.name).toBe("status");
    expect(providerCredentials.encryptedMaterial.name).toBe(
      "encrypted_material",
    );
    expect(getTableName(providerCredentialEvents)).toBe(
      "provider_credential_events",
    );
    expect(getTableName(userEnvironmentVariables)).toBe(
      "user_environment_variables",
    );
    expect(userEnvironmentVariables.encryptedValue.name).toBe(
      "encrypted_value",
    );
    expect(getTableName(userComputeUsage)).toBe("user_compute_usage");
    expect(userComputeUsage.minutesUsed.name).toBe("minutes_used");
    expect(getTableName(sandboxRuntimeIntervals)).toBe(
      "sandbox_runtime_intervals",
    );
    expect(sandboxRuntimeIntervals.endedAt.name).toBe("ended_at");
    expect(users.passwordHash.name).toBe("password_hash");
    expect(users.googleUserId.name).toBe("google_user_id");
    expect(providerCredentials.scopeType.name).toBe("scope_type");
    expect(providerCredentials.encryptedAccessToken.name).toBe(
      "encrypted_access_token",
    );
    expect(providerCredentials.awsRoleArn.name).toBe("aws_role_arn");
    expect(publishedBranches.sourceHeadSha.name).toBe("source_head_sha");
    expect(publishedBranches.remoteRef.name).toBe("remote_ref");
    expect(publishedBranches.pullRequestNumber.name).toBe(
      "pull_request_number",
    );
    expect(publishedBranches.pullRequestUrl.name).toBe("pull_request_url");
    expect(yjsSnapshots.conflictResolvedBy.name).toBe("conflict_resolved_by");
  });
});
