import "server-only";

import { desc, eq } from "drizzle-orm";
import OpenAI from "openai";

import { schema } from "@codev/db";

import { getOpenAIApiKey } from "./credentials";
import { getDatabase } from "./database";
import { getOpenAIModel } from "./ai-model";
import {
  openWorkspacePullRequest,
  type PullRequestError,
} from "./github-pull-request";
import {
  publishWorkspaceBranch,
  type PublicationError,
} from "./github-publication";

const SUMMARY_INPUT_BUDGET = 80_000;
const SUMMARY_FIELD_LIMIT = 4_000;

function compactSummaryValue(value: unknown) {
  if (typeof value === "string") return value.slice(0, SUMMARY_FIELD_LIMIT);
  if (
    value === null ||
    typeof value === "number" ||
    typeof value === "boolean"
  ) {
    return value;
  }
  try {
    return JSON.stringify(value).slice(0, SUMMARY_FIELD_LIMIT);
  } catch {
    return "[unserializable]";
  }
}

export function buildExportActivity(
  events: ReadonlyArray<{ type: string; payload: unknown }>,
) {
  const activity: Array<{ type: string; payload: Record<string, unknown> }> =
    [];
  let remaining = SUMMARY_INPUT_BUDGET;
  for (const event of [...events].reverse()) {
    const payload =
      event.payload &&
      typeof event.payload === "object" &&
      !Array.isArray(event.payload)
        ? Object.fromEntries(
            Object.entries(event.payload).map(([key, value]) => [
              key,
              compactSummaryValue(value),
            ]),
          )
        : { value: compactSummaryValue(event.payload) };
    const entry = { type: event.type, payload };
    const cost = JSON.stringify(entry).length;
    if (cost > remaining) break;
    activity.push(entry);
    remaining -= cost;
  }
  return activity;
}

export class GitHubExportError extends Error {
  constructor(
    message: string,
    readonly status = 409,
  ) {
    super(message);
    this.name = "GitHubExportError";
  }
}

export async function generateExportSummary(input: {
  workspaceId: string;
  userId: string;
  branchName: string;
}) {
  const [workspace] = await getDatabase()
    .select({ repository: schema.workspaces.repository })
    .from(schema.workspaces)
    .where(eq(schema.workspaces.id, input.workspaceId))
    .limit(1);
  if (!workspace) throw new GitHubExportError("Workspace not found.", 404);

  const events = await getDatabase()
    .select({
      type: schema.agentEvents.type,
      payload: schema.agentEvents.payload,
    })
    .from(schema.agentEvents)
    .where(eq(schema.agentEvents.workspaceId, input.workspaceId))
    .orderBy(desc(schema.agentEvents.createdAt))
    .limit(40);
  const apiKey = await getOpenAIApiKey(input.userId).catch(() => null);
  if (!apiKey) {
    throw new GitHubExportError(
      "Add an OpenAI API key in Settings before creating an AI-summarized pull request.",
      409,
    );
  }

  const client = new OpenAI({ apiKey });
  const response = await client.responses.create({
    model: getOpenAIModel(),
    reasoning: { effort: "low" },
    instructions:
      "Write a concise GitHub pull request summary from the CoDev workspace activity. Use Markdown. Include a Summary section and a Tests section. Never claim a test passed unless the activity explicitly shows it.",
    input: JSON.stringify({
      repository: workspace.repository,
      branch: input.branchName,
      recentWorkspaceActivity: buildExportActivity(events),
    }),
  });
  const summary = response.output_text?.trim();
  if (!summary) throw new GitHubExportError("The AI summary was empty.", 502);
  return summary.slice(0, 9_000);
}

export async function exportWorkspaceToPullRequest(input: {
  workspaceId: string;
  userId: string;
  branchName: string;
  expectedHeadSha: string;
  requestId: string;
}) {
  const summary = await generateExportSummary(input);
  const publication = await publishWorkspaceBranch(input);
  const pullRequest = await openWorkspacePullRequest({
    workspaceId: input.workspaceId,
    userId: input.userId,
    branchName: input.branchName,
    title: `CoDev: ${input.branchName}`,
    body: `${summary}\n\n---\nGenerated by CoDev from workspace activity.`,
    requestId: input.requestId,
  });
  return { publication, pullRequest, summary };
}

export type GitHubExportDependencyError = PublicationError | PullRequestError;
